import { createContext, useContext, useState, useCallback } from 'react'

const LanguageContext = createContext({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
})

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState('en')

  const setLang = useCallback((newLang) => {
    setLangState(newLang)
  }, [])

  const t = useCallback(
    (key, vars = {}) => {
      let text = translations[lang]?.[key] ?? translations['en']?.[key] ?? key
      Object.entries(vars).forEach(([k, v]) => {
        text = text.replace(new RegExp(`{${k}}`, 'g'), v)
      })
      return text
    },
    [lang]
  )

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}

const translations = {
  en: {
    // App / Header / Nav
    dailyTarotGuidance: 'Daily Tarot Guidance',
    readings: 'Readings',
    journal: 'Journal',
    mood: 'Mood',
    viewDisclaimer: 'View disclaimer',
    footerText: 'For entertainment and self-reflection purposes only. Not a substitute for professional advice.',

    // HomePage
    findClarity: 'Find clarity,',
    trustYourIntuition: 'trust your intuition',
    archetypalWisdom: 'Archetypal wisdom for mindful reflection. Begin your daily practice.',
    dailyCard: 'Daily Card',
    oneCardDailyInsight: 'One card, daily insight',
    pastPresentFuture: 'Past \u00b7 Present \u00b7 Future',
    timelineReading: 'Timeline reading',
    spreadLibrary: 'Spread Library',
    whatClarity: 'What would you like clarity on? (optional)',
    beginReading: 'Begin Reading',
    cancel: 'Cancel',

    // ReadingView
    back: 'Back',
    cardReading: 'card reading',
    theCardsAreAligning: 'The cards are aligning...',
    tapCardToReveal: 'Tap a card to reveal its message',
    cardMeanings: 'Card Meanings',
    todayInsight: "Today's Insight",
    todayReversed: 'Today, {name} (reversed) invites gentle self-reflection. {meaning} This is a moment to pause, breathe, and trust the process of inner growth.',
    todayUpright: 'Today, {name} (upright) brings supportive energy your way. {meaning} Embrace this guidance as you navigate your day with intention.',
    reversed: 'Reversed',
    rev: 'Rev',

    // ShufflingAnimation
    focusOnQuestion: 'Focus on your question...',
    breatheDeeply: 'Breathe deeply, let your mind settle',
    cardsAligningWithEnergy: 'The cards are aligning with your energy',
    yourReadingIsReady: 'Your reading is ready...',

    // AIInterpreter
    quickInsight: 'Quick Insight',
    deepReading: 'Deep Reading',
    generateReading: 'Generate Reading',
    readingComplete: 'Reading Complete',
    freeDailyQuota: 'Free daily quota: {count}/1',
    upgradeForUnlimited: 'Upgrade for unlimited readings',
    dearOne: 'Dear one,',
    drawnCard: 'Today the cards have drawn you **{name}** \u2014 and there\'s something beautiful waiting for you here.',
    aiPoweredInsight: 'AI-Powered Insight',
    personalizedReading: 'Personalized reading interpretation',
    yourQuestion: 'Your question',
    freeToday: 'Free today',
    comeBackTomorrow: 'Come back tomorrow',
    deepReadingDesc: '500+ words \u00b7 Guidance \u00b7 Action steps',
    craftingReading: 'Crafting your reading...',
    chooseAnother: 'Choose another reading type',
    somethingWrong: 'Something went wrong. Please try again.',
    aiDisclaimer: 'AI-generated readings are for self-reflection and entertainment. They don\'t replace professional guidance.',

    // Journal
    myReflections: 'My Reflections',
    newEntry: 'New Entry',
    title: 'Title',
    howAreYouFeeling: 'How are you feeling?',
    writeYourThoughts: 'Write your thoughts...',
    saveEntry: 'Save Entry',
    noEntriesYet: 'No entries yet.',
    startWriting: 'Start writing your first reflection.',
    delete: 'Delete',
    expand: 'Expand',

    // MoodTracker
    moodTracker: 'Mood Tracker',
    logTodaysMood: 'Log today\'s mood',
    inspired: 'Inspired',
    hopeful: 'Hopeful',
    calm: 'Calm',
    energetic: 'Energetic',
    reflective: 'Reflective',
    uncertain: 'Uncertain',
    averageMood: 'Average Mood',
    totalDays: 'Total Days',
    moodHistory: 'Mood History',
    noMoodData: 'No mood data yet.',

    // DailyCheckin
    streak: 'Streak',
    totalDaysCheckin: 'Total Days',
    readingPasses: 'Reading Passes',
    checkIn: 'Check In',
    checkedIn: 'Checked In',
    dayReward: 'Day {day} Reward',
    milestoneReached: 'Milestone reached',

    // HistoryJournal
    readingHistory: 'Reading History',
    noHistory: 'No readings yet.',
    wasAccurate: 'Was this accurate?',
    yes: 'Yes',
    notReally: 'Not really',
    clearAll: 'Clear All',
    confirmClear: 'Are you sure you want to clear all history?',

    // Disclaimer
    entertainmentReflection: 'Entertainment & Reflection',
    notProfessionalAdvice: 'Not Professional Advice',
    aiGenerated: 'AI-Generated Readings',
    privacy: 'Privacy',
    ageRequirement: 'Age Requirement',
    accept: 'I understand and accept',
    proceed: 'Proceed',
    disclaimerEntertainmentBody: 'For entertainment and self-reflection purposes only. Not a substitute for professional advice.',
    disclaimerProfessionalBody: 'If you\'re facing significant life decisions, we encourage consulting qualified professionals — therapists, counselors, or legal advisors.',
    disclaimerAIBody: 'Our AI interpretations are generated using large language models. While we aim for thoughtful, empathetic responses, they may not always be accurate or applicable to your situation.',
    disclaimerPrivacyBody: 'All your reading history, journal entries, and mood data are stored locally on your device. We don\'t collect, upload, or share any personal information.',
    disclaimerAgeBody: 'Users under 18 should use this app with parental guidance. Please don\'t use Loran Tarot for any unlawful or harmful purposes.',

    // Spread names (from spreadData)
    singleSpread: 'Single Card',
    threeSpread: 'Past \u00b7 Present \u00b7 Future',
    holyTrinity: 'Holy Trinity',
    crossroads: 'Crossroads',
    connection: 'Connection',
    celticCross: 'Celtic Cross',

    // Spread descriptions
    singleDesc: 'One card for daily insight and guidance.',
    threeDesc: 'Timeline reading covering your past influences, present situation, and future possibilities.',
    holyTrinityDesc: 'Body, mind, and spirit alignment reading.',
    crossroadsDesc: 'Clarity for decision-making between two paths.',
    connectionDesc: 'Insight into relationship dynamics and growth.',
    celticCrossDesc: 'Comprehensive ten-card spread for deep exploration.',

    // Position names
    past: 'Past',
    present: 'Present',
    future: 'Future',
    body: 'Body',
    mind: 'Mind',
    spirit: 'Spirit',
    situation: 'Situation',
    challenge: 'Challenge',
    foundation: 'Foundation',
    recentPast: 'Recent Past',
    bestOutcome: 'Best Outcome',
    self: 'Self',
    environment: 'Environment',
    hopes: 'Hopes',
    outcome: 'Outcome',
    pathA: 'Path A',
    pathB: 'Path B',
    advice: 'Advice',
    you: 'You',
    partner: 'Partner',
    dynamic: 'Dynamic',
    todayEnergy: "Today's Energy",
    rootCause: 'Root Cause',
    currentState: 'Current State',
    guidance: 'Guidance',
    outcomeA: 'Outcome A',
    outcomeB: 'Outcome B',
    yourBlock: 'Your Block',
    theirBlock: 'Their Block',
    trajectory: 'Trajectory',

    // Position meanings
    meaningTodayEnergy: 'The core energy and universal guidance to focus on today.',
    meaningPast: 'Past influences shaping your current situation.',
    meaningPresent: 'The energy and circumstances you\'re navigating right now.',
    meaningFuture: 'The direction things are heading based on current trends.',
    meaningRootCause: 'The underlying cause behind your current situation.',
    meaningCurrentState: 'The core energy you\'re experiencing right now.',
    meaningGuidance: 'The universe\'s guidance and advice moving forward.',
    meaningSituation: 'The core crossroads you\'re facing.',
    meaningPathA: 'What you\'ll experience if you choose the first option.',
    meaningOutcomeA: 'The likely result of choosing Path A.',
    meaningPathB: 'What you\'ll experience if you choose the second option.',
    meaningOutcomeB: 'The likely result of choosing Path B.',
    meaningYou: 'Your true feelings about this connection.',
    meaningPartner: 'The other person\'s true feelings about this connection.',
    meaningDynamic: 'The core state of the relationship right now.',
    meaningYourBlock: 'The inner obstacle you need to work through.',
    meaningTheirBlock: 'The obstacle the other person needs to work through.',
    meaningTrajectory: 'Where this relationship is heading.',
    meaningCelticPresent: 'The heart of the matter and your current situation.',
    meaningChallenge: 'What\'s crossing you — the immediate obstacle.',
    meaningFoundation: 'What\'s beneath — your subconscious drivers.',
    meaningCelticPast: 'What\'s behind you — influences that are fading.',
    meaningBestOutcome: 'What\'s above — your highest potential or goal.',
    meaningRecentPast: 'What\'s ahead — events coming soon.',
    meaningSelf: 'How you see yourself in this situation.',
    meaningEnvironment: 'How others see you and external influences.',
    meaningHopes: 'Your deepest hopes or underlying fears.',
    meaningOutcome: 'The likely resolution based on all current energies.',
    privateReflections: 'Your private reflections',
    titleOptional: 'Title (optional)',
    whatsOnYourMind: "What's on your mind? What insights did today's reading bring?",
    trackEmotionalJourney: 'Track your emotional journey',
    daysLogged: 'Days Logged',
    outOf5: 'out of 5',
    last30Days: 'last 30 days',
    dailyCheckin: 'Daily Check-in',
    buildYourPractice: 'Build your practice, one day at a time',
    progress: 'Progress',
    checkin7Days: 'Check in 7 days in a row to earn a Deep Reading Pass',
    checkedInToday: 'Checked in today. See you tomorrow',
    deepReadingPassAdded: 'Deep Reading Pass \u00d7 1 added to your account',
    readingsWillAppear: 'Your readings will appear here once you start.',
    spreadReading: 'Spread Reading',
    aQuickNote: 'A Quick Note',
    pleaseRead: 'Please read before continuing',
    important: 'Important',
    auraDesignedFor: 'Loran Tarot is designed for entertainment and self-reflection. It does not provide medical, psychological, or legal advice.',
    maybeLater: 'Maybe later',
    chooseReadingStyle: 'Choose your reading style',
    membersOnly: 'Members Only',
    unlockAllSpreads: 'Unlock All Spreads',
    unlockAllSpreadsDesc: 'Get access to Crossroads, Connection, Celtic Cross and more.',
    becomeMember: 'Become a Member',
    connectingToIntuition: 'Connecting to your intuition...',
    untitledReflection: 'Untitled Reflection',
  },
  zh: {
    // App / Header / Nav
    dailyTarotGuidance: '每日塔罗',
    readings: '牌阵',
    journal: '日记',
    mood: '心情',
    viewDisclaimer: '查看免责声明',
    footerText: '仅供娱乐和自我反思之用，不能替代专业建议。',

    // HomePage
    findClarity: '聆听内心，',
    trustYourIntuition: '让直觉引路',
    archetypalWisdom: '每一张牌都是一面镜子，映照当下的你。静心抽取，开启今日对话。',
    dailyCard: '每日一牌',
    oneCardDailyInsight: '一张牌，读懂今天',
    pastPresentFuture: '过去 \u00b7 现在 \u00b7 未来',
    timelineReading: '时间线解读',
    spreadLibrary: '更多牌阵',
    whatClarity: '你想问什么？（选填）',
    beginReading: '开始占卜',
    cancel: '取消',

    // ReadingView
    back: '返回',
    cardReading: '张牌',
    theCardsAreAligning: '塔罗牌正在排列中...',
    tapCardToReveal: '点击牌面揭示信息',
    cardMeanings: '牌意解读',
    todayInsight: '今日启示',
    todayReversed: '今天，{name}（逆位）邀请你进行温柔的自我反思。{meaning} 这是一个停下来、深呼吸、并相信内在成长过程的时刻。',
    todayUpright: '今天，{name}（正位）为你带来了支持性的能量。{meaning} 带着这份指引，有意识地度过你的一天。',
    reversed: '逆位',
    rev: '逆位',

    // ShufflingAnimation
    focusOnQuestion: '静心冥想你的问题...',
    breatheDeeply: '深呼吸，让思绪沉淀',
    cardsAligningWithEnergy: '牌在感应你的能量',
    yourReadingIsReady: '准备就绪...',

    // AIInterpreter
    quickInsight: '快速解读',
    deepReading: '深度解读',
    generateReading: '生成解读',
    readingComplete: '解读完成',
    freeDailyQuota: '今日免费次数：{count}/1',
    upgradeForUnlimited: '升级以获取无限次数',
    dearOne: '亲爱的，',
    drawnCard: '今天塔罗牌为你抽到了 **{name}** \u2014 这里有美好的事物在等待着你。',
    aiPoweredInsight: 'AI 智能解读',
    personalizedReading: '个性化占卜解读',
    yourQuestion: '你的问题',
    freeToday: '今日免费',
    comeBackTomorrow: '明日再来',
    deepReadingDesc: '500+ 字 \u00b7 指引 \u00b7 行动建议',
    craftingReading: '正在生成解读...',
    chooseAnother: '选择其他解读类型',
    somethingWrong: '出了点问题，请重试。',
    aiDisclaimer: 'AI 生成的解读仅供自我反思和娱乐之用，不能替代专业指导。',

    // Journal
    myReflections: '我的反思',
    newEntry: '新建日记',
    title: '标题',
    howAreYouFeeling: '你感觉如何？',
    writeYourThoughts: '写下你的想法...',
    saveEntry: '保存',
    noEntriesYet: '还没有日记。',
    startWriting: '写下你的第一篇反思。',
    delete: '删除',
    expand: '展开',

    // MoodTracker
    moodTracker: '心情追踪',
    logTodaysMood: '记录今天的心情',
    inspired: '受到启发',
    hopeful: '充满希望',
    calm: '平静',
    energetic: '精力充沛',
    reflective: '反思中',
    uncertain: '不确定',
    averageMood: '平均心情',
    totalDays: '总天数',
    moodHistory: '心情历史',
    noMoodData: '还没有心情数据。',

    // DailyCheckin
    streak: '连续签到',
    totalDaysCheckin: '总天数',
    readingPasses: '解读次数',
    checkIn: '签到',
    checkedIn: '已签到',
    dayReward: '第{day}天奖励',
    milestoneReached: '达成里程碑',

    // HistoryJournal
    readingHistory: '占卜历史',
    noHistory: '还没有占卜记录。',
    wasAccurate: '这次占卜准确吗？',
    yes: '是',
    notReally: '不太准',
    clearAll: '清空全部',
    confirmClear: '确定要清空所有历史记录吗？',

    // Disclaimer
    entertainmentReflection: '娱乐与反思',
    notProfessionalAdvice: '非专业建议',
    aiGenerated: 'AI 生成解读',
    privacy: '隐私保护',
    ageRequirement: '年龄要求',
    accept: '我已阅读并接受',
    proceed: '继续',
    disclaimerEntertainmentBody: '本应用仅供娱乐和自我反思之用，不能替代任何专业建议。',
    disclaimerProfessionalBody: '如果你正面临重大人生决定，建议咨询专业人士——心理咨询师、职业顾问或法律顾问。',
    disclaimerAIBody: 'AI 解读由大语言模型生成。虽然我们力求回复贴心、有启发，但内容不一定完全准确或适用于你的具体情况。',
    disclaimerPrivacyBody: '你的所有占卜记录、日记和心情数据均存储在本地设备上，我们不会收集、上传或分享任何个人信息。',
    disclaimerAgeBody: '未满 18 岁的用户请在家长指导下使用。请勿将本应用用于任何违法或有害目的。',

    // Spread names
    singleSpread: '单张牌',
    threeSpread: '过去 \u00b7 现在 \u00b7 未来',
    holyTrinity: '圣三角',
    crossroads: '二选一',
    connection: '关系发展',
    celticCross: '凯尔特十字',

    // Spread descriptions
    singleDesc: '一张牌，获取每日洞见与指引。',
    threeDesc: '涵盖过去影响、当下状况和未来可能性的时间线牌阵。',
    holyTrinityDesc: '身、心、灵对齐牌阵。',
    crossroadsDesc: '在两条路之间做出决定的清晰指引。',
    connectionDesc: '关系动态与成长的洞察。',
    celticCrossDesc: '十张牌综合牌阵，深度探索。',

    // Position names
    past: '过去',
    present: '现在',
    future: '未来',
    body: '身',
    mind: '心',
    spirit: '灵',
    situation: '现状',
    challenge: '挑战',
    foundation: '根基',
    recentPast: '近期过去',
    bestOutcome: '最佳结果',
    self: '自我',
    environment: '环境',
    hopes: '期望',
    outcome: '结果',
    pathA: '选项A',
    pathB: '选项B',
    advice: '建议',
    you: '你',
    partner: '对方',
    dynamic: '动态',
    todayEnergy: '今日能量',
    rootCause: '根本原因',
    currentState: '当前状态',
    guidance: '指引',
    outcomeA: '选项A结果',
    outcomeB: '选项B结果',
    yourBlock: '你的障碍',
    theirBlock: '对方的障碍',
    trajectory: '发展趋势',

    // Position meanings
    meaningTodayEnergy: '今天需要关注的核心能量与宇宙指引。',
    meaningPast: '正在影响你当下处境的过去经历。',
    meaningPresent: '你当前正在经历的能量和状况。',
    meaningFuture: '基于现有趋势事情可能的走向。',
    meaningRootCause: '你当前状况背后的深层原因。',
    meaningCurrentState: '你正在经历的核心能量。',
    meaningGuidance: '宇宙给予你的指引和建议。',
    meaningSituation: '你当前面临的核心抉择。',
    meaningPathA: '如果选择第一条路，你将会经历什么。',
    meaningOutcomeA: '选择路径A的可能结果。',
    meaningPathB: '如果选择第二条路，你将会经历什么。',
    meaningOutcomeB: '选择路径B的可能结果。',
    meaningYou: '你对这段关系的真实感受。',
    meaningPartner: '对方对这段关系的真实感受。',
    meaningDynamic: '这段关系当前的核心状态。',
    meaningYourBlock: '你需要面对的内在障碍。',
    meaningTheirBlock: '对方需要面对的障碍。',
    meaningTrajectory: '这段关系的走向。',
    meaningCelticPresent: '事情的核心以及你的当前状况。',
    meaningChallenge: '你正面临的直接障碍。',
    meaningFoundation: '你潜意识中的深层驱动力。',
    meaningCelticPast: '正在消退的过去影响。',
    meaningBestOutcome: '你最高的潜能或目标。',
    meaningRecentPast: '即将到来的事件。',
    meaningSelf: '你如何看待自己在此情境中的角色。',
    meaningEnvironment: '他人如何看待你以及外部影响。',
    meaningHopes: '你内心深处的希望或潜在的恐惧。',
    meaningOutcome: '基于当前所有能量的可能结局。',
    privateReflections: '你的私人反思',
    titleOptional: '标题（可选）',
    whatsOnYourMind: '你在想什么？今天的占卜给你带来了什么启示？',
    trackEmotionalJourney: '追踪你的情绪旅程',
    daysLogged: '已记录天数',
    outOf5: '满分 5 分',
    last30Days: '近 30 天',
    dailyCheckin: '每日签到',
    buildYourPractice: '每天练习，逐步积累',
    progress: '进度',
    checkin7Days: '连续签到 7 天可获得一次深度解读机会',
    checkedInToday: '今日已签到，明天见',
    deepReadingPassAdded: '深度解读次数 +1 已添加到你的账户',
    readingsWillAppear: '开始占卜后，你的记录将出现在这里。',
    spreadReading: '牌阵占卜',
    aQuickNote: '温馨提示',
    pleaseRead: '继续前请先阅读',
    important: '重要提示',
    auraDesignedFor: 'Loran Tarot 仅供娱乐和自我反思之用，不能提供医疗、心理或法律建议。',
    maybeLater: '稍后再说',
    chooseReadingStyle: '选择你的占卜方式',
    membersOnly: '仅限会员',
    unlockAllSpreads: '解锁所有牌阵',
    unlockAllSpreadsDesc: '获取二选一、关系发展、凯尔特十字等更多牌阵。',
    becomeMember: '成为会员',
    connectingToIntuition: '正在连接你的直觉...',
    untitledReflection: '无标题反思',
  },
}

export default LanguageContext
